version: 1
validation: sovereign
default_denom: reward
accounts: 
- name: alice
  coins:
  - 20000reward
  - 200000000reward
- name: bob
  coins:
  - 10000reward
  - 100000000reward
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5reward
  - 100000reward
validators:
- name: alice
  bonded: 100000000reward
- name: validator1
  bonded: 200000000reward
- name: validator2
  bonded: 100000000reward